# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/UIMainWindowForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowForm(object):
    def setupUi(self, MainWindowForm):
        MainWindowForm.setObjectName("MainWindowForm")
        MainWindowForm.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowForm)
        self.centralwidget.setObjectName("centralwidget")
        MainWindowForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindowForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowForm)
        self.statusbar.setObjectName("statusbar")
        MainWindowForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindowForm)
        self.toolBar.setObjectName("toolBar")
        MainWindowForm.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_DB_File = QtWidgets.QAction(MainWindowForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/offset_check/icons/tree.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_DB_File.setIcon(icon)
        self.actionOpen_DB_File.setObjectName("actionOpen_DB_File")
        self.actionOpen_SPS_File = QtWidgets.QAction(MainWindowForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/offset_check/icons/folder-open-document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_SPS_File.setIcon(icon1)
        self.actionOpen_SPS_File.setObjectName("actionOpen_SPS_File")
        self.actionQuit = QtWidgets.QAction(MainWindowForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/offset_check/icons/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen_DB_File)
        self.menuFile.addAction(self.actionOpen_SPS_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindowForm)
        self.actionQuit.triggered.connect(MainWindowForm.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindowForm)

    def retranslateUi(self, MainWindowForm):
        _translate = QtCore.QCoreApplication.translate
        MainWindowForm.setWindowTitle(_translate("MainWindowForm", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindowForm", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindowForm", "toolBar"))
        self.actionOpen_DB_File.setText(_translate("MainWindowForm", "Open DB File"))
        self.actionOpen_DB_File.setToolTip(_translate("MainWindowForm", "Open SQLite DB File"))
        self.actionOpen_SPS_File.setText(_translate("MainWindowForm", "Open SPS File"))
        self.actionQuit.setText(_translate("MainWindowForm", "Quit"))
import resources_rc
