# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/UIWarning.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UIWarning(object):
    def setupUi(self, UIWarning):
        UIWarning.setObjectName("UIWarning")
        UIWarning.resize(432, 170)
        UIWarning.setMinimumSize(QtCore.QSize(432, 170))
        UIWarning.setMaximumSize(QtCore.QSize(432, 170))
        self.buttonBox = QtWidgets.QDialogButtonBox(UIWarning)
        self.buttonBox.setGeometry(QtCore.QRect(10, 130, 409, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(UIWarning)
        self.label.setGeometry(QtCore.QRect(10, 20, 411, 91))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(UIWarning)
        self.buttonBox.accepted.connect(UIWarning.accept)
        QtCore.QMetaObject.connectSlotsByName(UIWarning)

    def retranslateUi(self, UIWarning):
        _translate = QtCore.QCoreApplication.translate
        UIWarning.setWindowTitle(_translate("UIWarning", "Warning"))
